// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://womcxbappudoglbtmnzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvbWN4YmFwcHVkb2dsYnRtbnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NDE1MjUsImV4cCI6MjA4NTAxNzUyNX0.osQrW2o8WPB3jMnjAhMmE6nuxa6a9Nn5CsdD1RV640k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});